# Generated by Django 6.0 on 2025-12-18 12:58

from django.db import migrations


def populate_categories(apps, schema_editor):
    Category = apps.get_model('categories', 'Category')
    predefined_categories = [
        'Groceries',
        'Transportation', 
        'Utilities',
        'Healthcare',
        'Entertainment',
        'Dining',
        'Clothing',
        'Education',
        'Bills',
        'Miscellaneous'
    ]
    
    for category_name in predefined_categories:
        Category.objects.get_or_create(name=category_name)


def reverse_populate_categories(apps, schema_editor):
    Category = apps.get_model('categories', 'Category')
    predefined_categories = [
        'Groceries',
        'Transportation', 
        'Utilities',
        'Healthcare',
        'Entertainment',
        'Dining',
        'Clothing',
        'Education',
        'Bills',
        'Miscellaneous'
    ]
    
    Category.objects.filter(name__in=predefined_categories).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_categories, reverse_populate_categories),
    ]
