# Generated by Django 5.2.7 on 2025-12-18 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['-date']},
        ),
        migrations.AddIndex(
            model_name='expenses',
            index=models.Index(fields=['user'], name='expenses_ex_user_id_845e3d_idx'),
        ),
        migrations.AddIndex(
            model_name='expenses',
            index=models.Index(fields=['date'], name='expenses_ex_date_d9f065_idx'),
        ),
        migrations.AddIndex(
            model_name='expenses',
            index=models.Index(fields=['category'], name='expenses_ex_categor_fa7234_idx'),
        ),
        migrations.AddIndex(
            model_name='expenses',
            index=models.Index(fields=['user', 'date'], name='expenses_ex_user_id_fe0ba0_idx'),
        ),
    ]
