# Generated by Django 6.0 on 2026-01-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expenses_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expenses',
            name='expenses_ex_user_id_845e3d_idx',
        ),
        migrations.RemoveIndex(
            model_name='expenses',
            name='expenses_ex_date_d9f065_idx',
        ),
        migrations.RemoveIndex(
            model_name='expenses',
            name='expenses_ex_categor_fa7234_idx',
        ),
        migrations.RemoveIndex(
            model_name='expenses',
            name='expenses_ex_user_id_fe0ba0_idx',
        ),
        migrations.AddField(
            model_name='expenses',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags (e.g., work,family,emergency)', max_length=200),
        ),
    ]
