# Generated by Django 6.0 on 2026-01-02 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_add_essential_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expenses',
            name='expenses_user_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='expenses',
            name='expenses_user_category_idx',
        ),
    ]
