# Generated by Django 6.0 on 2026-01-02 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_populate_predefined_categories'),
        ('expenses', '0005_remove_expenses_expenses_user_date_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expenses',
            index=models.Index(fields=['user', 'date'], name='expenses_ex_user_id_fe0ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='expenses',
            index=models.Index(fields=['user', 'category'], name='expenses_ex_user_id_2c554d_idx'),
        ),
        migrations.AddIndex(
            model_name='expenses',
            index=models.Index(fields=['date'], name='expenses_ex_date_d9f065_idx'),
        ),
    ]
